{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" $ }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: ecommerce
  {{- if eq $name "frontend" }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ecommerce-poc-frontend
  {{- end }}
spec:
  type: {{ if eq $name "frontend" }}{{ $.Values.service.type | default "ClusterIP" }}{{ else }}ClusterIP{{ end }}
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: {{ $service.port | default $.Values.service.port }}
      targetPort: http
---
{{- end }}
